#!/usr/bin/env bash
###############################################################################
# env_12node.sh - 12 节点环境变量配置
###############################################################################

export SEED_K3S_MASTER_IP="${SEED_K3S_MASTER_IP:-192.168.122.110}"
export SEED_K3S_WORKER1_IP="${SEED_K3S_WORKER1_IP:-192.168.122.111}"
export SEED_K3S_WORKER2_IP="${SEED_K3S_WORKER2_IP:-192.168.122.112}"
export SEED_K3S_WORKER3_IP="${SEED_K3S_WORKER3_IP:-192.168.122.113}"
export SEED_K3S_WORKER4_IP="${SEED_K3S_WORKER4_IP:-192.168.122.114}"
export SEED_K3S_WORKER5_IP="${SEED_K3S_WORKER5_IP:-192.168.122.115}"
export SEED_K3S_WORKER6_IP="${SEED_K3S_WORKER6_IP:-192.168.122.116}"
export SEED_K3S_WORKER7_IP="${SEED_K3S_WORKER7_IP:-192.168.122.117}"
export SEED_K3S_WORKER8_IP="${SEED_K3S_WORKER8_IP:-192.168.122.118}"
export SEED_K3S_WORKER9_IP="${SEED_K3S_WORKER9_IP:-192.168.122.119}"
export SEED_K3S_WORKER10_IP="${SEED_K3S_WORKER10_IP:-192.168.122.120}"
export SEED_K3S_WORKER11_IP="${SEED_K3S_WORKER11_IP:-192.168.122.121}"
export SEED_K3S_ALL_NODE_IPS="${SEED_K3S_ALL_NODE_IPS:-${SEED_K3S_MASTER_IP} ${SEED_K3S_WORKER1_IP} ${SEED_K3S_WORKER2_IP} ${SEED_K3S_WORKER3_IP} ${SEED_K3S_WORKER4_IP} ${SEED_K3S_WORKER5_IP} ${SEED_K3S_WORKER6_IP} ${SEED_K3S_WORKER7_IP} ${SEED_K3S_WORKER8_IP} ${SEED_K3S_WORKER9_IP} ${SEED_K3S_WORKER10_IP} ${SEED_K3S_WORKER11_IP}}"

export SEED_K3S_USER="${SEED_K3S_USER:-ubuntu}"
export SEED_K3S_SSH_KEY="${SEED_K3S_SSH_KEY:-$HOME/.ssh/id_ed25519}"

export SEED_K3S_CLUSTER_NAME="${SEED_K3S_CLUSTER_NAME:-seedemu-k3s}"
export SEED_CLUSTER_INVENTORY="${SEED_CLUSTER_INVENTORY:-seedemu-k3s-12node}"
export SEED_CLUSTER_INVENTORY_PATH="${SEED_CLUSTER_INVENTORY_PATH:-${HOME}/k8s/configs/clusters/seedemu-k3s-12node.yaml}"

export SEED_TOPOLOGY_SIZE="${SEED_TOPOLOGY_SIZE:-9955}"
export SEED_REAL_TOPOLOGY_DIR="${SEED_REAL_TOPOLOGY_DIR:-$HOME/seed-emulator/topology}"
export SEED_NAMESPACE="${SEED_NAMESPACE:-seedemu-k3s-real-topo}"

export SEED_REGISTRY="${SEED_REGISTRY:-${SEED_K3S_MASTER_IP}:5000}"
export SEED_REGISTRY_HOST="${SEED_REGISTRY_HOST:-${SEED_K3S_MASTER_IP}}"
export SEED_REGISTRY_PORT="${SEED_REGISTRY_PORT:-5000}"
export SEED_CNI_TYPE="${SEED_CNI_TYPE:-macvlan}"
export SEED_CNI_MASTER_INTERFACE="${SEED_CNI_MASTER_INTERFACE:-ens2}"
export SEED_SCHEDULING_STRATEGY="${SEED_SCHEDULING_STRATEGY:-by_as_hard}"
export SEED_PLACEMENT_MODE="${SEED_PLACEMENT_MODE:-by_as_hard}"
export SEED_IMAGE_PULL_POLICY="${SEED_IMAGE_PULL_POLICY:-IfNotPresent}"
export SEED_IMAGE_DISTRIBUTION_MODE="${SEED_IMAGE_DISTRIBUTION_MODE:-preload}"

export SEED_BUILD_PARALLELISM="${SEED_BUILD_PARALLELISM:-8}"
export SEED_BUILD_BATCH_SIZE="${SEED_BUILD_BATCH_SIZE:-50}"
export SEED_DOCKER_BUILDKIT="${SEED_DOCKER_BUILDKIT:-1}"
export SEED_COMPOSE_DOCKER_CLI_BUILD="${SEED_COMPOSE_DOCKER_CLI_BUILD:-1}"
export SEED_PRELOAD_BATCH_SIZE="${SEED_PRELOAD_BATCH_SIZE:-10}"

export DEPLOY_BATCH_SIZE="${DEPLOY_BATCH_SIZE:-20}"
export DEPLOY_BATCH_SLEEP_SECONDS="${DEPLOY_BATCH_SLEEP_SECONDS:-40}"
export DEPLOY_MONITOR_INTERVAL="${DEPLOY_MONITOR_INTERVAL:-20}"
export DEPLOY_WARMUP_BATCHES="${DEPLOY_WARMUP_BATCHES:-5}"
export DEPLOY_WARMUP_BATCH_SIZE="${DEPLOY_WARMUP_BATCH_SIZE:-5}"
export DEPLOY_PRESSURE_CHECK_SECONDS="${DEPLOY_PRESSURE_CHECK_SECONDS:-15}"
export DEPLOY_STABILIZE_TIMEOUT_SECONDS="${DEPLOY_STABILIZE_TIMEOUT_SECONDS:-7200}"
export DEPLOY_MAX_PENDING_PODS="${DEPLOY_MAX_PENDING_PODS:-60}"
export DEPLOY_MAX_CREATING_PODS="${DEPLOY_MAX_CREATING_PODS:-100}"
export DEPLOY_MAX_NOTREADY_PODS="${DEPLOY_MAX_NOTREADY_PODS:-150}"
export DEPLOY_MAX_FAILED_PODS="${DEPLOY_MAX_FAILED_PODS:-5}"

export SEED_KVM_UBUNTU_SERIES="${SEED_KVM_UBUNTU_SERIES:-jammy}"
export SEED_KVM_BASE_IMAGE_URL="${SEED_KVM_BASE_IMAGE_URL:-https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img}"
export SEED_KVM_BASE_IMAGE_PATH="${SEED_KVM_BASE_IMAGE_PATH:-${HOME}/k8s/output/kvm_lab/base/jammy-server-cloudimg-amd64.img}"

export OUTPUT_DIR="${OUTPUT_DIR:-${HOME}/k8s/lxl/output}"
export LOG_BASE_DIR="${LOG_BASE_DIR:-${HOME}/k8s/lxl/logs}"
export CLEAN_NAMESPACE="${CLEAN_NAMESPACE:-true}"

create_experiment_dir() {
    if [ -n "${EXPERIMENT_DIR:-}" ] && [ -d "${EXPERIMENT_DIR}" ]; then
        export EXPERIMENT_DIR="$(cd "${EXPERIMENT_DIR}" && pwd)"
        mkdir -p "${EXPERIMENT_DIR}"
        return 0
    fi
    local timestamp
    timestamp="$(date +%Y%m%d_%H%M%S)"
    export EXPERIMENT_DIR="${LOG_BASE_DIR}/${timestamp}_${SEED_TOPOLOGY_SIZE}"
    mkdir -p "${EXPERIMENT_DIR}"
}

log_start() {
    local script_name="$1"
    echo "[$(date +%H:%M:%S)] ${script_name} started" >> "${EXPERIMENT_DIR}/timings.txt"
}

log_end() {
    local script_name="$1"
    echo "[$(date +%H:%M:%S)] ${script_name} completed" >> "${EXPERIMENT_DIR}/timings.txt"
}
