#!/usr/bin/env bash

# Stable build/preload defaults for the 12-node test flow.
export SEED_BUILD_PARALLELISM="${SEED_BUILD_PARALLELISM:-4}"
export SEED_BUILD_BATCH_SIZE="${SEED_BUILD_BATCH_SIZE:-50}"
export SEED_DOCKER_BUILDKIT="${SEED_DOCKER_BUILDKIT:-1}"
export SEED_COMPOSE_DOCKER_CLI_BUILD="${SEED_COMPOSE_DOCKER_CLI_BUILD:-1}"
export SEED_PRELOAD_BATCH_SIZE="${SEED_PRELOAD_BATCH_SIZE:-10}"
export SEED_PRELOAD_NODE_CONCURRENCY="${SEED_PRELOAD_NODE_CONCURRENCY:-3}"
export SEED_REGISTRY_PUSH_RETRIES="${SEED_REGISTRY_PUSH_RETRIES:-5}"
export SEED_REGISTRY_PUSH_BACKOFF_SECONDS="${SEED_REGISTRY_PUSH_BACKOFF_SECONDS:-5}"
export SEED_REGISTRY_PUSH_TIMEOUT_SECONDS="${SEED_REGISTRY_PUSH_TIMEOUT_SECONDS:-180}"
