#!/usr/bin/env bash

# Conservative deploy defaults. Safe for 1078 on 12 nodes.
export DEPLOY_BATCH_SIZE="${DEPLOY_BATCH_SIZE:-20}"
export DEPLOY_BATCH_SLEEP_SECONDS="${DEPLOY_BATCH_SLEEP_SECONDS:-20}"
export DEPLOY_MONITOR_INTERVAL="${DEPLOY_MONITOR_INTERVAL:-20}"
export DEPLOY_WARMUP_BATCHES="${DEPLOY_WARMUP_BATCHES:-3}"
export DEPLOY_WARMUP_BATCH_SIZE="${DEPLOY_WARMUP_BATCH_SIZE:-5}"
export DEPLOY_PRESSURE_CHECK_SECONDS="${DEPLOY_PRESSURE_CHECK_SECONDS:-10}"
export DEPLOY_STABILIZE_TIMEOUT_SECONDS="${DEPLOY_STABILIZE_TIMEOUT_SECONDS:-3600}"
export DEPLOY_MAX_PENDING_PODS="${DEPLOY_MAX_PENDING_PODS:-100}"
export DEPLOY_MAX_CREATING_PODS="${DEPLOY_MAX_CREATING_PODS:-150}"
export DEPLOY_MAX_NOTREADY_PODS="${DEPLOY_MAX_NOTREADY_PODS:-250}"
export DEPLOY_MAX_FAILED_PODS="${DEPLOY_MAX_FAILED_PODS:-5}"

export SEED_WAIT_READY_INTERVAL_SECONDS="${SEED_WAIT_READY_INTERVAL_SECONDS:-30}"
export SEED_WAIT_READY_TIMEOUT_SECONDS="${SEED_WAIT_READY_TIMEOUT_SECONDS:-3600}"
